apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: argo-workflows-role
rules:
  - apiGroups:
      - ""
      - "argoproj.io"
    resources:
      - "workflows"
      - "workflowtaskresults"
      - "pods"
      - "pods/log"
      - "configmaps"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: argo-workflows-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: argo-workflows-role
  apiGroup: rbac.authorization.k8s.io

