apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repository
  namespace: gourmetgram-dev
data:
  artifactRepository: |
    s3:
      endpoint: minio:9000
      bucket: argo-artifacts
      accessKeySecret:
        name: minio-credentials
        key: accesskey
      secretKeySecret:
        name: minio-credentials
        key: secretkey
      insecure: true

