---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: gourmetgram-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-notebook
  namespace: gourmetgram-dev
  labels:
    app: pytorch-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch-notebook
  template:
    metadata:
      labels:
        app: pytorch-notebook
    spec:
      containers:
      - name: notebook
        image: quay.io/jupyter/pytorch-notebook:cpu-pytorch-2.5.1
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: data-volume
          mountPath: /content/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-notebook
  namespace: gourmetgram-dev
spec:
  selector:
    app: pytorch-notebook
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP
