apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    name: data-pvc
    namespace: gourmetgram-dev
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: gourmetgram-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-notebook
  namespace: gourmetgram-dev
  labels:
    app: pytorch-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch-notebook
  template:
    metadata:
      labels:
        app: pytorch-notebook
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/jovyan/work"]
        volumeMounts:
        - name: data-volume
          mountPath: /home/jovyan/work
      containers:
      - name: notebook
        image: quay.io/jupyter/pytorch-notebook:pytorch-2.5.1
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: "1"   # Request 1 vCPU
            memory: "2Gi" # Request 2GiB RAM
          limits:
            cpu: "2"      # Max usage 2 vCPUs
            memory: "4Gi" # Max usage 4GiB RAM
        command: ["start-notebook.sh"]
        args:
          - "--IdentityProvider.token=''"
          - "--ServerApp.password=''"
          - "--ServerApp.ip=0.0.0.0"   # Listen on all interfaces
        volumeMounts:
        - name: data-volume
          mountPath: /home/jovyan/work
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "your-access-key"
          - name: AWS_SECRET_ACCESS_KEY
            value: "your-secret-key"
          - name: AWS_S3_ENDPOINT
            value: "minio:9000"
          - name: FOOD11_DATA_DIR
            value: "/tmp/food11"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-notebook
  namespace: gourmetgram-dev
spec:
  selector:
    app: pytorch-notebook
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP
