apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage 
  claimRef:
    name: minio-pvc
    namespace: gourmetgram-dev
  hostPath:
    path: "/mnt/data"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: gourmetgram-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: gourmetgram-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "your-access-key"
            - name: MINIO_ROOT_PASSWORD
              value: "your-secret-key"
          ports:
          - containerPort: 9000
            name: api
          - containerPort: 9001
            name: web-ui
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: gourmetgram-dev
spec:
  selector:
    app: minio
  ports:
    - name: web-ui
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: gourmetgram-dev
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
