---
- name: Install ArgoCD CLI
  hosts: node1  
  become: yes
  tasks:
    - name: Download ArgoCD CLI binary
      get_url:
        url: "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
        dest: "/usr/local/bin/argocd"
        mode: '0755'

    - name: Verify ArgoCD CLI installation
      command: argocd version
      register: argocd_version
      ignore_errors: yes

    - name: Show ArgoCD version
      debug:
        msg: "{{ argocd_version.stdout_lines }}"
