apiVersion: v1
kind: Service
metadata:
  name: gourmetgram-kube-svc
  namespace: gourmetgram-staging
spec:
  selector:
    app: gourmetgram-kube-app
  ports:
    - protocol: "TCP"
      port: 80          # Service port inside the cluster
      targetPort: 8000  # Forward to the pod's port 8000
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gourmetgram-kube-app
  namespace: gourmetgram-staging
spec:
  selector:
    matchLabels:
      app: gourmetgram-kube-app
  replicas: 2
  template:
    metadata:
      labels:
        app: gourmetgram-kube-app
    spec:
      containers:
      - name: gourmetgram-kube-app
        image: registry.kube-system.svc.cluster.local:5000/gourmetgram-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /test
            port: 8000
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 3
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.3"
            memory: "300Mi"
