apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-docker-config
  namespace: argo
data:
  config.json: |
    {
      "insecure-registries": ["registry.kube-system.svc.cluster.local:5000"]
    }

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-initial
spec:
  entrypoint: build-process
  volumes:
    - name: shared-workspace
      emptyDir: {}
    - name: docker-config
      configMap:
        name: kaniko-docker-config

  templates:
    - name: build-process
      steps:
        - - name: clone-repo
            template: git-clone
        - - name: kaniko-build
            template: kaniko-build

    - name: git-clone
      script:
        image: alpine/git
        command: [sh]
        source: |
          set -eux
          git clone --branch master https://github.com/teaching-on-testbeds/gourmetgram.git /workspace/src
          ls -la /workspace/src
        volumeMounts:
          - name: shared-workspace
            mountPath: /workspace

    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - "--dockerfile=/workspace/src/Dockerfile"
          - "--context=/workspace/src"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:canary"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:staging"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:production"
          - "--insecure"
          - "--cache=true"
        volumeMounts:
          - name: shared-workspace
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker
