apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-docker-config
  namespace: argo
data:
  config.json: |
    {
      "insecure-registries": ["registry.kube-system.svc.cluster.local:5000"]
    }

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-initial
spec:
  entrypoint: build-from-branch
  volumes:
    - name: git-source
      emptyDir: {}
    - name: docker-config
      configMap:
        name: kaniko-docker-config
  templates:

  - name: build-from-branch
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: kaniko-build
          template: kaniko-build

  - name: git-clone
    container:
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
        - |
          git clone --branch master https://github.com/teaching-on-testbeds/gourmetgram.git /src
      volumeMounts:
        - name: git-source
          mountPath: /src

  - name: kaniko-build
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: ["/kaniko/executor"]
      args:
        - "--dockerfile=Dockerfile"
        - "--context=/src"
        - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:canary"
        - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:staging"
        - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:production"
        - "--insecure"
        - "--cache=true"
      volumeMounts:
        - name: git-source
          mountPath: /src
        - name: docker-config
          mountPath: /kaniko/.docker

