apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-docker-config
  namespace: argo
data:
  config.json: |
    {
      "insecure-registries": ["registry.kube-system.svc.cluster.local:5000"]
    }

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-initial
spec:
  entrypoint: kaniko-direct-build
  volumes:
    - name: docker-config
      configMap:
        name: kaniko-docker-config

  templates:
    - name: kaniko-direct-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - "--context=https://github.com/teaching-on-testbeds/gourmetgram.git"
          - "--dockerfile=Dockerfile"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:canary"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:staging"
          - "--destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:production"
          - "--insecure"
          - "--cache=true"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker