---
- name: Disable and Mask firewalld
  hosts: all
  become: yes  # Run tasks as root

  tasks:
    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Mask firewalld service
      systemd:
        name: firewalld
        masked: yes
