replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/gourmetgram-app
  tag: production

service:
  port: 80
  externalIP: ""   # Placeholder

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

